images: node:latest

pages:
  stage: deploy
  script:
    - npm config set registry https://registry.npm.js.com
    - npm i
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - dist
      
  only:
    - master

